# ---------- Stage 1: Build ----------
FROM nginx:alpine AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y ca-certificates openssl
RUN update-ca-certificates

ENV NODE_OPTIONS=--openssl-legacy-provider

RUN npm config set fetch-retries 5 \
 && npm config set fetch-retry-mintimeout 20000 \
 && npm config set fetch-retry-maxtimeout 120000

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

# ---------- Production ----------
FROM nginx:alpine 

WORKDIR /app

RUN npm install -g serve

COPY --from=builder /app/dist ./dist

EXPOSE 5173

CMD ["serve", "-s", "dist", "-l", "5173"]